systNameDict = {
    'Stat':'Statistical',
    'MCGEN':'ME generator',
    'JES1':'LHC JES 1',
    'BTAG':'b tagging',
    'HADR':'Hadronization',
    'JESFLV':'LHC JES 4',
    'TOPPT':'Top quark \pt',
    'PDF':'PDFs',
    'JES2':'LHC JES 2',
    'RAD':'QCD radiation',
    'CR':'Color reconnection',
    'JER':'Jet energy resolution',
    'BKMC':'Backround (simulation)',
    'LES':'Lepton energy scale',
    'METH':'Method',
    'UE':'Underlying event',
    'PU':'Pileup',
    'JES3':'LHC JES 3',
    'JES7':'LHC JES 7', # to remove
    'BKDT':'Background (data)',
    'AtlJetUnc':'ATLAS jet reconstruction',
    'MET':'Missing transverse energy',
    'Extra':'Extra', # to check
    'AtlFastFull':'ATLAS fast simulation',
    'TRIG':'Trigger efficiency',
    'JES8':'LHC JES 8', # to remove
    'CMSJES1':'CMS JES 1',
    'BFRAG':'b quark fragmentation',
    'SLEPB':'Semileptonic B-hadron BR',
    'Q':'ME scale',
    'JPS':'ME/PS matching',
    'CMSFL1':'LHC JES 4',
}
